#pragma once


typedef enum MXLOGGER_STATUS_CODE
{
	MXLOGGER_INIT_SUCCESSFULLY = 0,
	MXLOGGER_INIT_FAILED,
	MXLOGGER_STATUS_ALLREADY_INITIALIZED,
	MXLOGGER_STATUS_INVALID_PARAMETER,

	// Read Status
	MXLOGGER_STATUS_CONFIG_READ_SUCCESS,
	MXLOGGER_STATUS_CONFIG_READ_INVALID_PATH,
	MXLOGGER_STATUS_CONFIG_READ_PATH_TOO_LONG,
	MXLOGGER_STATUS_CONFIG_READ_INVALID_CHARACTERS,
	MXLOGGER_STATUS_CONFIG_READ_DIRECTORY_TRAVERSAL,
	MXLOGGER_STATUS_CONFIG_READ_FILE_NOT_EXIST,
	MXLOGGER_STATUS_CONFIG_READ_NOT_A_FILE,
	MXLOGGER_STATUS_CONFIG_READ_FILE_NOT_READABLE,
	MXLOGGER_STATUS_CONFIG_READ_FILE_TOO_LARGE,
	MXLOGGER_STATUS_CONFIG_READ_OPEN_FAILED,
	MXLOGGER_STATUS_CONFIG_READ_READ_FAILED,
	MXLOGGER_STATUS_CONFIG_READ_OPERATION_FAILED,

	// parse status
	MXLOGGER_STATUS_CONFIG_PARSE_JSON_EMPTY,
	MXLOGGER_STATUS_CONFIG_PARSE_JSON_VALID,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_JSON_FORMAT,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_QUEUE_CAPACITY,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_LOG_OUTPUT,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_FILE_PATH,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_ROTATION_FILES,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_ROTATION_FILE_SIZE,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_UDP_HOST,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_UDP_PORT,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_HTTP_HOST,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_HTTP_PORT,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_HTTP_ENDPOINT,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_MODULE_NAME,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_MODULE_CONFIG,

	MXLOGGER_STATUS_CONFIG_PARSE_MISSING_REQUIRED_FIELD,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_FORMATE_TYPE,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_FIELD_TYPE,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_PATH_LENGTH,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_HOST_LENGTH,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_IP,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_PORT,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_ENDPOINT_LENGTH,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_LOG_LEVEL,
	MXLOGGER_STATUS_CONFIG_PARSE_INVALID_MODULE_FILTER,

	MXLOGGER_STATUS_CONFIG_PARSE_SUCCESS,
	MXLOGGER_STATUS_CONFIG_PARSE_FAILED,

} MXLOGGER_STATUS_CODE;


typedef enum LOGLEVEL
{
	Trace = 0,
	Debug = 1,
	Info = 2,
	Warning = 3,
	Error = 4,
	Critical = 5
} LOGLEVEL;