#pragma once
#ifndef MEDIA_TYPES_H
#define MEDIA_TYPES_H

// Media type macros for video formats
#define MEDIA_TYPE_VIDEO_H264     "video/H264"
#define MEDIA_TYPE_VIDEO_X_H264   "video/x-h264"
#define MEDIA_TYPE_VIDEO_H265     "video/H265"
#define MEDIA_TYPE_VIDEO_X_H265   "video/x-h265"
#define MEDIA_TYPE_VIDEO_MPEG     "video/mpeg"
#define MEDIA_TYPE_VIDEO_MJPEG    "video/mjpeg"
#define MEDIA_TYPE_VIDEO_JPEG     "video/jpeg"
#define MEDIA_TYPE_VIDEO_MP4V     "video/mp4v"
#define MEDIA_TYPE_VIDEO_MPEG2    "video/mpeg2video"
#define MEDIA_TYPE_VIDEO_MPEG4    "video/mpeg4"
#define MEDIA_TYPE_VIDEO_RAW      "video/raw"
#define MEDIA_TYPE_VIDEO_SV3V     "video/sv3v"
#define MEDIA_TYPE_VIDEO_H263     "video/h263"
#define MEDIA_TYPE_VIDEO_H263P    "video/h263p"
#define MEDIA_TYPE_VIDEO_THEORA   "video/theora"
#define MEDIA_TYPE_VIDEO_VP8      "video/vp8"
#define MEDIA_TYPE_VIDEO_VP9      "video/vp9"
#define MEDIA_TYPE_VIDEO_VC1      "video/vc1"
#define MEDIA_TYPE_VIDEO_DV       "video/dv"

// Media type macros for audio formats
#define MEDIA_TYPE_AUDIO_AAC      "audio/aac"
#define MEDIA_TYPE_AUDIO_MP3      "audio/mp3"
#define MEDIA_TYPE_AUDIO_OPUS     "audio/opus"
#define MEDIA_TYPE_AUDIO_ALAW     "audio/x-alaw"
#define MEDIA_TYPE_AUDIO_ULAW     "audio/x-ulaw"
#define MEDIA_TYPE_AUDIO_G729     "audio/g729"
#define MEDIA_TYPE_AUDIO_WMA      "audio/wma"
#define MEDIA_TYPE_AUDIO_ALAC     "audio/alac"
#define MEDIA_TYPE_AUDIO_MPEG     "audio/mpeg"
#define MEDIA_TYPE_AUDIO_MPEG2    "audio/mpeg2"
#define MEDIA_TYPE_AUDIO_AC3      "audio/ac3"
#define MEDIA_TYPE_AUDIO_FLAC     "audio/flac"
#define MEDIA_TYPE_AUDIO_WAV      "audio/wav"
#define MEDIA_TYPE_AUDIO_VORBIS   "audio/vorbis"
#define MEDIA_TYPE_AUDIO_GSM      "audio/gsm"
#define MEDIA_TYPE_AUDIO_AMR      "audio/amr"
#define MEDIA_TYPE_AUDIO_AMR_WB   "audio/amr-wb"
#define MEDIA_TYPE_AUDIO_SPEEX    "audio/speex"
#define MEDIA_TYPE_AUDIO_PN_REAL_AUDIO     "audio/pn-realaudio"

//container type macors
#define MEDIA_CONTAINER_TYPE_MP4			  "mp4"
#define MEDIA_CONTAINER_TYPE_AVI			  "avi"				
#define MEDIA_CONTAINER_TYPE_FLV			  "flv"
#define MEDIA_CONTAINER_TYPE_OGG			  "ogg"
#define MEDIA_CONTAINER_TYPE_DV				  "dv"
#define MEDIA_CONTAINER_TYPE_CAF			  "caf"
#define MEDIA_CONTAINER_TYPE_MXF			  "mxf"
#define MEDIA_CONTAINER_TYPE_M3U8			  "m3u8"
#define MEDIA_CONTAINER_TYPE_MP3			  "mp3"
#define MEDIA_CONTAINER_TYPE_RM				  "rm"
#define MEDIA_CONTAINER_TYPE_RMVB			  "rmvb"
#define MEDIA_CONTAINER_TYPE_RA				  "ra"
#define MEDIA_CONTAINER_TYPE_RAM			  "ram"
#define MEDIA_CONTAINER_TYPE_MKV			  "mkv"
#define MEDIA_CONTAINER_TYPE_MKA			  "mka"
#define MEDIA_CONTAINER_TYPE_MOV			  "mov"
#define MEDIA_CONTAINER_TYPE_WEBM			  "webm"
#define MEDIA_CONTAINER_TYPE_TS				  "ts"
#define MEDIA_CONTAINER_TYPE_M2TS			  "m2ts"
#define MEDIA_CONTAINER_TYPE_MTS			  "mts"
#define MEDIA_CONTAINER_TYPE_MPG			  "mpg"
#define MEDIA_CONTAINER_TYPE_MPEG			  "mpeg"
#define MEDIA_CONTAINER_TYPE_VOB			  "vob"
#define MEDIA_CONTAINER_TYPE_ASF		      "asf"
#define MEDIA_CONTAINER_TYPE_WMA		      "wma"
#define MEDIA_CONTAINER_TYPE_WMV		      "wmv"
#define MEDIA_CONTAINER_TYPE_3G2		      "3g2"
#define MEDIA_CONTAINER_TYPE_3GP		      "3gp"

//path type micro for tempory used
#define MEDIA_INPUT_PATH					  "D:\\Input\\H265_codec.mp4"
#define MEDIA_OUTPUT_PATH					  "D:\\Output\\trans1.avi"

// Add more media types as needed
#endif // MEDIA_TYPES_H
